trigger:
  name: Push to release
  identifier: Push_to_release
  enabled: true
  description: Auto-run on create/push to release/** branches (deploys to TEST).
  orgIdentifier: default
  projectIdentifier: myfirst
  pipelineIdentifier: Build_daveKoala_repo_consume_pipeline_modules_1782394589089
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: Push
        spec:
          connectorRef: account.Github
          autoAbortPreviousExecutions: true
          payloadConditions:
            - key: targetBranch
              operator: Regex
              value: ^release/.*$
          headerConditions: []
          repoName: daveKoala/repo_consume_pipeline_modules
          actions: []
  pipelineBranchName: main
  inputSetRefs:
    - Build_daveKoala_repo_consume_pipeline_modules_1782394589089pushtriggerinputset
