trigger:
  name: Push to feature
  identifier: Push_to_feature
  enabled: true
  description: Auto-run on push to feature/** branches (deploys to DEV).
  orgIdentifier: default
  projectIdentifier: myfirst
  pipelineIdentifier: Develop_daveKoala_repo_consume_pipeline_modules
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: Push
        spec:
          connectorRef: account.Github
          autoAbortPreviousExecutions: true
          payloadConditions:
            - key: targetBranch
              operator: Regex
              value: ^feature/.*$
          headerConditions: []
          repoName: daveKoala/repo_consume_pipeline_modules
          actions: []
  pipelineBranchName: main
  inputSetRefs:
    - Develop_daveKoala_repo_consume_pipeline_modulespushtriggerinputset
