pipeline:
  identifier: Build_daveKoala_repo_consume_pipeline_modules_1782394589089
  name: Build repo_consume_pipeline_modules
  orgIdentifier: default
  projectIdentifier: myfirst
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: daveKoala/repo_consume_pipeline_modules
  stages:
    - stage:
        name: pre-build
        identifier: prebuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo "Pre Build step"
                  description: pre build
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: |-
                      echo "Build ID: <+pipeline.sequenceId>"
                      echo "Execution ID: <+pipeline.executionId>"

                      echo "Repo: <+codebase.repoName>"
                      echo "Branch: <+codebase.branch>"
                      echo "Commit SHA: <+codebase.commitSha>"
                      echo "Commit Message: <+codebase.commitMessage>"
                      echo "Author: <+codebase.commitAuthor>"

                      echo "Triggered by: <+trigger.triggeredBy.name>"
                  description: build id
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - parallel:
                  - step:
                      identifier: echo
                      name: echo
                      spec:
                        command: echo hello world
                      timeout: ""
                      type: Run
                  - step:
                      type: Run
                      name: Run_2
                      identifier: Run_2
                      spec:
                        shell: Sh
                        command: echo "Yoooo Hooooo"
                      description: yooo hoo
              - step:
                  type: Run
                  name: Run_3
                  identifier: Run_3
                  spec:
                    shell: Sh
                    command: echo "Another step"
                  description: another-step
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
